Completed prep-javascript-variables.
Robinson-Tyler/prep-0422-code-solutions pull request #10
Opened 2022-04-23 22:17 UTC by Robinson-Tyler

![image](https://user-images.githubusercontent.com/103710393/164947805-baf1e885-7d38-4ac5-9044-0f929fc62ca3.png)

2022-04-25 23:47 UTC, thebearingedge requested changes

2022-04-25 23:47 UTC, thebearingedge commented on prep-javascript-variables/index.html
> +    var nothing = 'null';
Hi Tyler, be sure to leave out the quotes from numbers, booleans, and `null` so that the browser doesn't interpret them as strings.

2022-04-26 06:17 UTC, Robinson-Tyler commented
![javascript variables edit](https://user-images.githubusercontent.com/103710393/165234317-67865a40-20a2-4c5d-bdd9-e31d2a318e11.PNG)

2022-04-27 15:29 UTC, thebearingedge approved these changes

2022-04-29 01:34 UTC, merged